// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc702egjPLPlcf0G1JUbrkTfrGe724me8',
    appId: '1:412368266806:web:7fdd61d4935e767e735a97',
    messagingSenderId: '412368266806',
    projectId: 'zbmtech-4b2c7',
    authDomain: 'zbmtech-4b2c7.firebaseapp.com',
    storageBucket: 'zbmtech-4b2c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYQOVxZiDq7lnBbGcAc3by36aB28Gnr2s',
    appId: '1:412368266806:android:8461937958ef0652735a97',
    messagingSenderId: '412368266806',
    projectId: 'zbmtech-4b2c7',
    storageBucket: 'zbmtech-4b2c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxPHvP62ekORogUBdjtlSj1c_HnIb7Adk',
    appId: '1:412368266806:ios:2b974c3aefdd74f0735a97',
    messagingSenderId: '412368266806',
    projectId: 'zbmtech-4b2c7',
    storageBucket: 'zbmtech-4b2c7.appspot.com',
    iosBundleId: 'com.example.task01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxPHvP62ekORogUBdjtlSj1c_HnIb7Adk',
    appId: '1:412368266806:ios:2b974c3aefdd74f0735a97',
    messagingSenderId: '412368266806',
    projectId: 'zbmtech-4b2c7',
    storageBucket: 'zbmtech-4b2c7.appspot.com',
    iosBundleId: 'com.example.task01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc702egjPLPlcf0G1JUbrkTfrGe724me8',
    appId: '1:412368266806:web:bd7055c1d3cb8d89735a97',
    messagingSenderId: '412368266806',
    projectId: 'zbmtech-4b2c7',
    authDomain: 'zbmtech-4b2c7.firebaseapp.com',
    storageBucket: 'zbmtech-4b2c7.appspot.com',
  );

}